name: job file handling
on:
  workflow_dispatch:
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Create a file with some content
              run: |
                echo "This is a sample file created by job1." > sample.txt
            - name: upload file as artifact
              uses: actions/upload-artifact@v3
              with:
                name: sample-file
                path: sample.txt
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: Download the artifact from job1
              uses: actions/download-artifact@v3
              with:
                name: sample-file
            - name: Display the content of the downloaded file
              run: |
                echo "Content of the downloaded file:"
                cat sample.txt